name: Algo Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'yarn' # Cache Yarn dependencies

      - name: Install Dependencies
        run: yarn install --frozen-lockfile # Use yarn for installation

      - name: Run Tests with Coverage
        run: yarn test --coverage # Run tests with yarn
        env:
          FORCE_COLOR: true
